### ISSUE TITLE
Unable to add to AltStore 

### ISSUE THREAD

**Issue by miIktoast** [Balackburn/YTLitePlusAltstore#1]
- select ‘Add to AltStore/Sidestore’
- AltStore opens
- 
![IMG_0526](https://github.com/Balackburn/YTLitePlusAltstore/assets/76277835/c47fad05-7268-41f9-9dde-f68ae0b1da32)

**Comment by Balackburn** [comment]
@miIktoast Hello I temporaly fixed it but will not close the issue until this is really fixed, could you try again?

the way the altstore 2.0 source work is unfortnualtly not really evident

**Comment by miIktoast** [comment]
Working.
