### ISSUE TITLE
source doesn't have latest version | issue in the YTLitePlus release page

### ISSUE THREAD

**Issue by bachig26** [Balackburn/YTLitePlusAltstore#2]
in the [Releases](https://github.com/Balackburn/YTLitePlus/releases) page, the latest version 18.45.2-2.4 doesn't show and can only view via the t[ag](https://github.com/Balackburn/YTLitePlus/tags).

@Balackburn so maybe that's why the source replaced the same version 18.44.3-2.4 when automated.

**Comment by Balackburn** [comment]
Hello this is an issue with my update script, when two releases where released the same day it don't choose the latest

I will update it

**Comment by Balackburn** [comment]
Fixed
