### ISSUE TITLE
source hasn't been updated ~ possible issue with workflow

### ISSUE THREAD

**Issue by bachig26** [Balackburn/YTLitePlusAltstore#4]
@Balackburn it's been couple of hours since the latest version [v18.46.3-2.4 - YTLitePlus](https://github.com/Balackburn/YTLitePlus/releases/tag/v18.46.3-2.4), but the source hasn't updated.

please have a look at the workflow/updater if there's any issue.

**Comment by Balackburn** [comment]
> @Balackburn it's been couple of hours since the latest version [v18.46.3-2.4 - YTLitePlus](https://github.com/Balackburn/YTLitePlus/releases/tag/v18.46.3-2.4), but the source hasn't updated.
> 
> 
> 
> please have a look at the workflow/updater if there's any issue.

Hello it was because the release was still in draft when the workflow was run, I manually ran it again.

**Comment by bachig26** [comment]
> Hello it was because the release was still in draft when the workflow was run, I manually ran it again.

oh okay, sorry.
